# Generated by Django 5.2 on 2025-07-08 20:30

import backend.accounts.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchableUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', backend.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SearchableUserActionLog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.useractionlog',),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_history',
            field=models.JSONField(default=list),
        ),
    ]
