# Generated by Django 5.2.4 on 2025-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_searchableuser_searchableuseractionlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
