# Generated by Django 5.2 on 2025-08-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_termosaceite_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="termosaceite",
            name="pdf_terms",
        ),
    ]
