# Generated by Django 5.1.4 on 2025-04-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_bm',
            name='apresentacao_na_unidade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
