# Generated by Django 5.1.4 on 2025-03-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='image',
            field=models.ImageField(max_length=255, upload_to='img/fotos_perfil'),
        ),
    ]
