# Generated by Django 5.2 on 2025-05-14 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhessituacao',
            name='cat_efetivo',
            field=models.CharField(choices=[('', ' '), ('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('LSV', 'LSV'), ('LTS', 'LTS'), ('LTS FAMILIA', 'LTS FAMILIA'), ('CONVAL', 'CONVAL'), ('ELEIÇÃO', 'ELEIÇAO'), ('LP', 'LP'), ('FERIAS', 'FÉRIAS'), ('RESTRICAO', 'RESTRIÇÃO')], default='Ativo', max_length=30),
        ),
        migrations.CreateModel(
            name='CatEfetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('LSV', 'LSV'), ('LTS', 'LTS'), ('LTS FAMILIA', 'LTS FAMILIA'), ('CONVAL', 'CONVAL'), ('ELEIÇÃO', 'ELEIÇÃO'), ('LP', 'LP'), ('FERIAS', 'FÉRIAS'), ('RESTRICAO', 'RESTRIÇÃO')], default='ATIVO', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('boletim_concessao_lsv', models.CharField(blank=True, max_length=50, null=True)),
                ('data_boletim_lsv', models.DateField(blank=True, null=True)),
                ('restricao_au', models.BooleanField(default=False, verbose_name='Audição seja primordial')),
                ('restricao_ou', models.BooleanField(default=False, verbose_name='Ordem unida')),
                ('restricao_bs', models.BooleanField(default=False, verbose_name='Busca e salvamento')),
                ('restricao_po', models.BooleanField(default=False, verbose_name='Policiamento')),
                ('restricao_cb', models.BooleanField(default=False, verbose_name='Corte de barba')),
                ('restricao_pq', models.BooleanField(default=False, verbose_name='Serviços com produtos químicos')),
                ('restricao_cc', models.BooleanField(default=False, verbose_name='Corte de cabelo')),
                ('restricao_pt', models.BooleanField(default=False, verbose_name='Prática de tiro')),
                ('restricao_ci', models.BooleanField(default=False, verbose_name='Correr para incêndio')),
                ('restricao_sa', models.BooleanField(default=False, verbose_name='Serviços aquáticos')),
                ('restricao_dg', models.BooleanField(default=False, verbose_name='Datilografia e Digitação')),
                ('restricao_sb', models.BooleanField(default=False, verbose_name='Serviços burocráticos')),
                ('restricao_dv', models.BooleanField(default=False, verbose_name='Dirigir veículo')),
                ('restricao_se', models.BooleanField(default=False, verbose_name='Serviços externos')),
                ('restricao_ef', models.BooleanField(default=False, verbose_name='Educação Física')),
                ('restricao_sg', models.BooleanField(default=False, verbose_name='Serviço de guarda')),
                ('restricao_em', models.BooleanField(default=False, verbose_name='Escrever a mão')),
                ('restricao_sh', models.BooleanField(default=False, verbose_name='Serviços em altura')),
                ('restricao_ep', models.BooleanField(default=False, verbose_name='Equilíbrio seja primordial')),
                ('restricao_si', models.BooleanField(default=False, verbose_name='Serviços internos')),
                ('restricao_es', models.BooleanField(default=False, verbose_name='Exposição ao sol')),
                ('restricao_sm', models.BooleanField(default=False, verbose_name='Serviços manuais')),
                ('restricao_fo', models.BooleanField(default=False, verbose_name='Formatura')),
                ('restricao_sn', models.BooleanField(default=False, verbose_name='Serviços noturnos')),
                ('restricao_is', models.BooleanField(default=False, verbose_name='Tocar instrumento de sopro')),
                ('restricao_sp', models.BooleanField(default=False, verbose_name='Serviços pesados')),
                ('restricao_lp', models.BooleanField(default=False, verbose_name='Longa permanência em pé')),
                ('restricao_st', models.BooleanField(default=False, verbose_name='Serviços de telefonia')),
                ('restricao_lr', models.BooleanField(default=False, verbose_name='Locais ruidosos')),
                ('restricao_ua', models.BooleanField(default=False, verbose_name='Uso de arma')),
                ('restricao_ls', models.BooleanField(default=False, verbose_name='Longa permanência sentado')),
                ('restricao_ub', models.BooleanField(default=False, verbose_name='Uso de botas')),
                ('restricao_uc', models.BooleanField(default=False, verbose_name='Uso de calçado esportivo')),
                ('restricao_ma', models.BooleanField(default=False, verbose_name='Manuseio com animais')),
                ('restricao_mc', models.BooleanField(default=False, verbose_name='Montar a cavalo')),
                ('restricao_mg', models.BooleanField(default=False, verbose_name='Mergulho')),
                ('restricao_mp', models.BooleanField(default=False, verbose_name='Manipulação de pó')),
                ('restricao_vp', models.BooleanField(default=False, verbose_name='Visão seja primordial')),
                ('restricao_uu', models.BooleanField(default=False, verbose_name='Uso de uniformes')),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_efetivo', to='efetivo.cadastro')),
                ('usuario_cadastro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoria de Efetivo',
                'verbose_name_plural': 'Categorias de Efetivo',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoCatEfetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('LSV', 'LSV'), ('LTS', 'LTS'), ('LTS FAMILIA', 'LTS FAMILIA'), ('CONVAL', 'CONVAL'), ('ELEIÇÃO', 'ELEIÇÃO'), ('LP', 'LP'), ('FERIAS', 'FÉRIAS'), ('RESTRICAO', 'RESTRIÇÃO')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('boletim_concessao_lsv', models.CharField(blank=True, max_length=50, null=True)),
                ('data_boletim_lsv', models.DateField(blank=True, null=True)),
                ('restricao_au', models.BooleanField(default=False, verbose_name='Audição seja primordial')),
                ('restricao_ou', models.BooleanField(default=False, verbose_name='Ordem unida')),
                ('restricao_bs', models.BooleanField(default=False, verbose_name='Busca e salvamento')),
                ('cat_efetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='efetivo.catefetivo')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Categoria de Efetivo',
                'verbose_name_plural': 'Históricos de Categorias de Efetivo',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='catefetivo',
            index=models.Index(fields=['tipo'], name='efetivo_cat_tipo_f85d38_idx'),
        ),
        migrations.AddIndex(
            model_name='catefetivo',
            index=models.Index(fields=['cadastro'], name='efetivo_cat_cadastr_9d53c8_idx'),
        ),
        migrations.AddIndex(
            model_name='catefetivo',
            index=models.Index(fields=['ativo'], name='efetivo_cat_ativo_bec96b_idx'),
        ),
        migrations.AddIndex(
            model_name='catefetivo',
            index=models.Index(fields=['data_inicio', 'data_termino'], name='efetivo_cat_data_in_5823a8_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocatefetivo',
            index=models.Index(fields=['cat_efetivo'], name='efetivo_his_cat_efe_e92877_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocatefetivo',
            index=models.Index(fields=['data_registro'], name='efetivo_his_data_re_205c96_idx'),
        ),
        migrations.AddIndex(
            model_name='historicocatefetivo',
            index=models.Index(fields=['tipo'], name='efetivo_his_tipo_1fb486_idx'),
        ),
    ]
