# Generated by Django 5.1.4 on 2025-03-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhessituacao',
            name='prontidao',
            field=models.CharField(choices=[('', ' '), ('VERDE', 'VERDE'), ('AMARELA', 'AMARELA'), ('AZUL', 'AZUL'), ('ADM', 'ADM')], default='', max_length=18),
        ),
        migrations.AddField(
            model_name='historicodetalhessituacao',
            name='prontidao',
            field=models.CharField(default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='detalhessituacao',
            name='op_adm',
            field=models.CharField(blank=True, choices=[('', ' '), ('Administrativo', ' Administrativo'), ('Operacional', 'Operacional')], max_length=18, null=True),
        ),
    ]
