# Generated by Django 5.1.4 on 2025-03-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0002_alter_imagem_image'),
        ('efetivo', '0002_detalhessituacao_prontidao_and_more'),
    ]

    operations = [
    ]
