# Generated by Django 5.2 on 2025-05-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0002_alter_detalhessituacao_cat_efetivo_catefetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_cb',
            field=models.BooleanField(default=False, verbose_name='Corte de barba'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_cc',
            field=models.BooleanField(default=False, verbose_name='Corte de cabelo'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_ci',
            field=models.BooleanField(default=False, verbose_name='Correr para incêndio'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_dg',
            field=models.BooleanField(default=False, verbose_name='Datilografia e Digitação'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_dv',
            field=models.BooleanField(default=False, verbose_name='Dirigir veículo'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_ef',
            field=models.BooleanField(default=False, verbose_name='Educação Física'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_em',
            field=models.BooleanField(default=False, verbose_name='Escrever a mão'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_ep',
            field=models.BooleanField(default=False, verbose_name='Equilíbrio seja primordial'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_es',
            field=models.BooleanField(default=False, verbose_name='Exposição ao sol'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_fo',
            field=models.BooleanField(default=False, verbose_name='Formatura'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_is',
            field=models.BooleanField(default=False, verbose_name='Tocar instrumento de sopro'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_lp',
            field=models.BooleanField(default=False, verbose_name='Longa permanência em pé'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_lr',
            field=models.BooleanField(default=False, verbose_name='Locais ruidosos'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_ls',
            field=models.BooleanField(default=False, verbose_name='Longa permanência sentado'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_ma',
            field=models.BooleanField(default=False, verbose_name='Manuseio com animais'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_mc',
            field=models.BooleanField(default=False, verbose_name='Montar a cavalo'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_mg',
            field=models.BooleanField(default=False, verbose_name='Mergulho'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_mp',
            field=models.BooleanField(default=False, verbose_name='Manipulação de pó'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_po',
            field=models.BooleanField(default=False, verbose_name='Policiamento'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_pq',
            field=models.BooleanField(default=False, verbose_name='Serviços com produtos químicos'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_pt',
            field=models.BooleanField(default=False, verbose_name='Prática de tiro'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_sa',
            field=models.BooleanField(default=False, verbose_name='Serviços aquáticos'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_sb',
            field=models.BooleanField(default=False, verbose_name='Serviços burocráticos'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_se',
            field=models.BooleanField(default=False, verbose_name='Serviços externos'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_sg',
            field=models.BooleanField(default=False, verbose_name='Serviço de guarda'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_sh',
            field=models.BooleanField(default=False, verbose_name='Serviços em altura'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_si',
            field=models.BooleanField(default=False, verbose_name='Serviços internos'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_sm',
            field=models.BooleanField(default=False, verbose_name='Serviços manuais'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_sn',
            field=models.BooleanField(default=False, verbose_name='Serviços noturnos'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_sp',
            field=models.BooleanField(default=False, verbose_name='Serviços pesados'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_st',
            field=models.BooleanField(default=False, verbose_name='Serviços de telefonia'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_ua',
            field=models.BooleanField(default=False, verbose_name='Uso de arma'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_ub',
            field=models.BooleanField(default=False, verbose_name='Uso de botas'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_uc',
            field=models.BooleanField(default=False, verbose_name='Uso de calçado esportivo'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_uu',
            field=models.BooleanField(default=False, verbose_name='Uso de uniformes'),
        ),
        migrations.AddField(
            model_name='historicocatefetivo',
            name='restricao_vp',
            field=models.BooleanField(default=False, verbose_name='Visão seja primordial'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='catefetivo',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
