# Generated by Django 5.1.4 on 2025-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0003_merge_20250317_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='image',
            field=models.ImageField(upload_to='img/fotos_perfil'),
        ),
    ]
