# Generated by Django 5.1.4 on 2025-04-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0003_alter_detalhessituacao_usuario_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhessituacao',
            name='cat_efetivo',
            field=models.CharField(choices=[('', ' '), ('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('LSV', 'LSV'), ('LTS', 'LTS'), ('LTS FAMILIA', 'LTS FAMILIA'), ('CONVAL', 'CONVAL'), ('ELEIÇÃO', 'ELEIÇAO'), ('LP', 'LP'), ('FERIAS', 'FÉRIAS')], default='Ativo', max_length=30),
        ),
        migrations.AlterField(
            model_name='detalhessituacao',
            name='situacao',
            field=models.CharField(choices=[('', ' '), ('Efetivo', 'Efetivo'), ('Exonerado a Pedido', 'Exonerado a Pedido'), ('Exonerado Ex-Ofício', 'Exonerado Ex-Ofício'), ('Reserva a Pedido', 'Reserva a Pedido'), ('Transferido', 'Transferido'), ('Mov. Interna', 'Mov. Interna')], default='Efetivo', max_length=30),
        ),
    ]
