# Generated by Django 5.2 on 2025-05-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0003_historicocatefetivo_restricao_cb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalhessituacao',
            name='cat_efetivo',
        ),
        migrations.AlterField(
            model_name='catefetivo',
            name='tipo',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('LSV', 'LSV'), ('LTS', 'LTS'), ('LTS FAMILIA', 'LTS FAMILIA'), ('CONVAL', 'CONVAL'), ('ELEIÇÃO', 'ELEIÇÃO'), ('LP', 'LP'), ('FERIAS', 'FÉRIAS'), ('RESTRICAO', 'RESTRIÇÃO'), ('DS', 'DS'), ('DR', 'DR')], default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicocatefetivo',
            name='tipo',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('LSV', 'LSV'), ('LTS', 'LTS'), ('LTS FAMILIA', 'LTS FAMILIA'), ('CONVAL', 'CONVAL'), ('ELEIÇÃO', 'ELEIÇÃO'), ('LP', 'LP'), ('FERIAS', 'FÉRIAS'), ('RESTRICAO', 'RESTRIÇÃO'), ('DS', 'DS'), ('DR', 'DR')], max_length=20),
        ),
    ]
