# Generated by Django 5.2 on 2025-05-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0004_remove_detalhessituacao_cat_efetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicocatefetivo',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
    ]
