# Generated by Django 5.2 on 2025-06-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0005_historicocatefetivo_deletado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catefetivo',
            name='tipo',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('LSV', 'LSV'), ('LTS', 'LTS'), ('LTS FAMILIA', 'LTS FAMILIA'), ('CONVAL', 'CONVAL'), ('ELEIÇÃO', 'ELEIÇÃO'), ('LP', 'LP'), ('FERIAS', 'FÉRIAS'), ('RESTRICAO', 'RESTRIÇÃO'), ('DS', 'DS'), ('DR', 'DR'), ('FOLGA_MENSAL', 'FOLGA MENSAL'), ('FOLGA_SEMANAL', 'FOLGA SEMANAL')], default='ATIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicocatefetivo',
            name='tipo',
            field=models.CharField(choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO'), ('LSV', 'LSV'), ('LTS', 'LTS'), ('LTS FAMILIA', 'LTS FAMILIA'), ('CONVAL', 'CONVAL'), ('ELEIÇÃO', 'ELEIÇÃO'), ('LP', 'LP'), ('FERIAS', 'FÉRIAS'), ('RESTRICAO', 'RESTRIÇÃO'), ('DS', 'DS'), ('DR', 'DR'), ('FOLGA_MENSAL', 'FOLGA MENSAL'), ('FOLGA_SEMANAL', 'FOLGA SEMANAL')], max_length=20),
        ),
    ]
