# Generated by Django 5.2 on 2025-06-12 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0006_alter_catefetivo_tipo_alter_historicocatefetivo_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhessituacao',
            name='cat_efetivo',
            field=models.CharField(blank=True, default='Efetivo', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='detalhessituacao',
            name='apresentacao_na_unidade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalhessituacao',
            name='cadastro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes_situacao', to='efetivo.cadastro'),
        ),
        migrations.AlterField(
            model_name='detalhessituacao',
            name='data_alteracao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='detalhessituacao',
            name='esta_adido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='detalhessituacao',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detalhessituacao',
            name='op_adm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalhessituacao',
            name='posto_secao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalhessituacao',
            name='prontidao',
            field=models.CharField(blank=True, default='', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='detalhessituacao',
            name='sgb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detalhessituacao',
            name='usuario_alteracao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicocatefetivo',
            name='tipo',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('LSV', 'LSV - Licença para Serviço Voluntário'), ('LTS', 'LTS - Licença para Tratamento de Saúde'), ('LTS FAMILIA', 'LTS Família - Licença para Tratamento de Saúde de Familiar'), ('CONVAL', 'Convalescença'), ('ELEIÇÃO', 'Eleição'), ('LP', 'Licença Prêmio'), ('FERIAS', 'Férias'), ('RESTRICAO', 'Restrição'), ('DS', 'Dispensado de Serviço'), ('DR', 'Dispensa Recompensa')], max_length=20),
        ),
    ]
