# Generated by Django 5.2 on 2025-06-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0008_alter_detalhessituacao_cadastro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicodetalhessituacao',
            options={'ordering': ['-data_alteracao'], 'verbose_name': 'Histórico de Detalhes de Situação', 'verbose_name_plural': 'Históricos de Detalhes de Situação'},
        ),
        migrations.AlterField(
            model_name='historicodetalhessituacao',
            name='apresentacao_na_unidade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicodetalhessituacao',
            name='cat_efetivo',
            field=models.CharField(blank=True, default='ATIVO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historicodetalhessituacao',
            name='esta_adido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicodetalhessituacao',
            name='funcao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicodetalhessituacao',
            name='op_adm',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicodetalhessituacao',
            name='posto_secao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicodetalhessituacao',
            name='prontidao',
            field=models.CharField(blank=True, default='', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicodetalhessituacao',
            name='sgb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicodetalhessituacao',
            name='situacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
