# Generated by Django 5.2 on 2025-07-14 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0009_alter_historicodetalhessituacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalhessituacao',
            options={'ordering': ['-data_alteracao']},
        ),
    ]
