# Generated by Django 5.2 on 2025-07-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0010_alter_detalhessituacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagem',
            options={'ordering': ['-create_at']},
        ),
    ]
