# Generated by Django 4.2.7 on 2025-11-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_presence_reaction_alter_attachment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Marca a mensagem como excluída",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["deleted_at"], name="chat_messag_deleted_73bd5c_idx"
            ),
        ),
    ]
