# Generated by Django 5.2 on 2025-10-31 18:44

import backend.tickets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(default=backend.tickets.models.gerar_protocolo, editable=False, max_length=20, unique=True)),
                ('solicitante_nome', models.CharField(max_length=150, verbose_name='Nome do Solicitante')),
                ('solicitante_email', models.EmailField(max_length=254, verbose_name='Email do Solicitante')),
                ('solicitante_cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF do Solicitante')),
                ('solicitante_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Solicitante')),
                ('assunto', models.CharField(max_length=255, verbose_name='Assunto')),
                ('descricao', models.TextField(verbose_name='Descrição do Problema')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_atendimento', 'Em Atendimento'), ('aguardando_usuario', 'Aguardando Resposta do Usuário'), ('resolvido', 'Resolvido'), ('fechado', 'Fechado')], default='aberto', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_resolucao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Resolução')),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Fechamento')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.categoria', verbose_name='Categoria')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_atribuidos', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_criados', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Registrado')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='chamados_anexos/%Y/%m/%d/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Anexo')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='tickets.chamado')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('privado', models.BooleanField(default=False, help_text='Comentários privados são visíveis apenas para a equipe técnica.', verbose_name='Comentário Privado')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tickets.chamado')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['criado_em'],
            },
        ),
    ]
