# Generated by Django 5.2 on 2025-11-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoria",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("gestao_usuarios", "Gestão de Usuários e Acessos"),
                    ("cadastro_efetivo", "Cadastro do Efetivo"),
                    ("relatorios_documentos", "Relatórios e Documentos"),
                    ("ferramentas_sistema", "Ferramentas do Sistema"),
                    ("cursos_qualificacoes", "Cursos e Qualificações"),
                    ("outros", "Outros"),
                ],
                max_length=50,
                verbose_name="Categoria do Problema",
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="subcategoria",
            field=models.CharField(
                choices=[
                    ("erro_login", "Erro ao fazer login"),
                    ("alteracao_senha", "Dificuldade para alterar a senha"),
                    ("problema_permissao", "Usuário sem permissão para uma área"),
                    ("cadastro_usuario", "Problema no cadastro de novo usuário"),
                    ("erro_buscar_militar", "Não consigo encontrar um militar"),
                    ("dados_desatualizados", "Dados do militar estão desatualizados"),
                    ("problema_promocao", "Erro ao registrar promoção"),
                    ("erro_situacao", "Erro ao alterar situação do militar"),
                    ("geracao_relatorio", "Relatório não gera ou apresenta erro"),
                    ("exportacao_dados", "Exportação de dados (CSV/Excel) falhou"),
                    ("upload_documento", "Não consigo anexar um documento"),
                    ("visualizacao_documento", "Erro ao visualizar um documento"),
                    ("erro_calculadora", "Erro na Calculadora"),
                    ("problema_agenda", "Problema na Agenda/Calendário"),
                    ("erro_busca_global", "Busca global não retorna resultados"),
                    ("inscricao_curso", "Erro ao inscrever em um curso"),
                    ("visualizacao_historico", "Histórico de cursos não aparece"),
                    ("duvida_geral", "Dúvida sobre como usar uma função"),
                    ("sugestao_melhoria", "Sugestão de melhoria para o sistema"),
                    ("outro_problema", "Outro tipo de problema não listado"),
                ],
                max_length=50,
                verbose_name="Subcategoria",
            ),
        ),
    ]
