# Generated by Django 5.1.4 on 2025-03-31 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faisca', '0002_faiscaagentconversation_faiscaagentchat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaiscaAgentQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('was_successful', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_time', models.FloatField(help_text='Tempo de execução em segundos')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Consulta do Faisca',
                'verbose_name_plural': 'Logs de Consultas do Faisca',
                'ordering': ['-created_at'],
            },
        ),
    ]
