# Generated by Django 5.1.4 on 2025-04-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faisca', '0004_indiceinterno_documentointerno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='arquivado',
        ),
        migrations.AddField(
            model_name='conversation',
            name='tipo',
            field=models.CharField(choices=[('geral', 'Geral'), ('interno', 'Interno')], default='geral', max_length=20),
        ),
    ]
