# Generated by Django 5.1.4 on 2025-04-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_rpt',
            name='status',
            field=models.CharField(choices=[('', ''), ('Aguardando', 'Aguardando'), ('Mov. serviço', 'Mov. serviço'), ('Mov. própria', 'Mov. própria'), ('Exclusão a pedido', 'Exclusão a pedido'), ('Transferido de Unidade', 'Transferido de Unidade'), ('Excluído Alt. quadro', 'Excluído Alt. quadro')], max_length=50),
        ),
    ]
