# Generated by Django 5.1.4 on 2025-04-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpt', '0003_rename_data_alteracao_to_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_rpt',
            name='data_alteracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicorpt',
            name='data_alteracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cadastro_rpt',
            name='status',
            field=models.CharField(choices=[('', ''), ('Aguardando', 'Aguardando'), ('Mov. serviço', 'Mov. serviço'), ('Mov. própria', 'Mov. própria'), ('Exclusão a pedido', 'Exclusão a pedido'), ('Transferido de Unidade', 'Transferido de Unidade'), ('Excluído Alt. quadro', 'Excluído Alt. quadro')], max_length=50),
        ),
    ]
