# Generated by Django 4.2.7 on 2025-11-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lembrete",
            name="data",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="data_fim",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="tarefa",
            name="data_inicio",
            field=models.DateTimeField(db_index=True),
        ),
    ]
