# Generated by Django 4.2.7 on 2025-11-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("municipios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cidade",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cidade",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cidade",
            name="posto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cidades",
                to="municipios.posto",
                verbose_name="Posto vinculado",
            ),
        ),
    ]
