# Generated by Django 5.2 on 2025-05-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='outro_curso',
        ),
    ]
