# Generated by Django 5.2 on 2025-06-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_curso_outro_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medalha',
            options={'ordering': ['-data_publicacao_lp'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso',
            field=models.CharField(choices=[('Atendimento Pré-Hospitalar Tático', 'Atendimento Pré-Hospitalar Tático'), ('Gestão pela Qualidade_Oficial', 'Gestão Contemporânea pela Qualidade'), ('Administração de Projetos', 'Administração de Projetos '), ('Gestão por Processos', 'Gestão por Processos '), ('Gestão Qualidade', 'Gestão Qualidade '), ('Comunicação Social', 'Comunicação Social '), ('Gestores de Defesa Civil', 'Gestores de Defesa Civil '), ('Operador RPAS', 'Operador de RPAS '), ('Tripulante Operacional', 'Tripulante Operacional'), ('Pressurização Escadas', ' Pressurização de Escadas '), ('Atendente COPOM', 'Atendente COPOM '), ('Ferramentas Inteligentes', 'Ferramentas Inteligentes '), ('Supervisão COPOM', 'Supervisão Operacional'), ('Operador COPOM', 'Operador de COPOM '), ('Investigação PM', 'Investigação PM'), ('PJM', 'Polícia Judiciária Militar '), ('Capacitação Tutores EAD', 'Capacitação de Tutores Ead'), ('Finanças Públicas', 'Finanças Públicas '), ('Auxiliar Encarregado Adiantamentos', 'Auxiliar de Encarregado de Adiantamentos '), ('Gestão de Contratos', 'Gestão de Contratos'), ('Técnico Logística', 'Técnico Logística '), ('Administrador Logística', 'Administrador Logística '), ('Operador RH', 'OOperador RH'), ('Técnico RH', 'Técnico em RH'), ('Administrador RH', 'Administrador RH'), ('CBEF', 'Ed Fisica PM'), ('OVB', 'OVB'), ('Abordagem Suicídio', 'Abordagem Suicídio '), ('CEP_Bombeiros_Civis', 'Bombeiros - Civis - 1'), ('Salvamento Aquático', 'Salvamento Aquático '), ('DREM', 'DREM'), ('REM', 'REM'), ('Produtos Perigosos', 'Produtos Perigosas'), ('CMAUT', 'CMAUT'), ('Operações Bote ', 'Operações com Bote '), ('Salvamento Terrestre', 'Salvamento Terrestre '), ('Salvamento Veicular', 'Salvamento Veicular'), ('Guarda-Vidas', 'Guarda-Vidas'), ('CSALT', 'CSALT'), ('MOB', 'MOB'), ('BREC', 'BREC'), ('CFS', 'CFS'), ('CBS', 'CBS'), ('CBCS', 'CBCS'), ('CBO', 'CBO'), ('Técnicas de Ensino', 'Técnicas de Ensino')], max_length=255),
        ),
    ]
