# Generated by Django 5.2 on 2025-06-15 12:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('efetivo', '0009_alter_historicodetalhessituacao_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Última Atualização')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('dias_desconto_lp', models.PositiveSmallIntegerField(default=0, verbose_name='Dias de Desconto LP')),
                ('numero_lp', models.PositiveSmallIntegerField(choices=[(1, '01º LP'), (2, '02º LP'), (3, '03º LP'), (4, '04º LP'), (5, '05º LP'), (6, '06º LP'), (7, '07º LP'), (8, '08º LP')], verbose_name='Número da LP')),
                ('data_ultimo_lp', models.DateField(verbose_name='Data do Último LP')),
                ('data_inicio_periodo', models.DateField(verbose_name='Início do Período Aquisitivo')),
                ('numero_prox_lp', models.PositiveSmallIntegerField(blank=True, choices=[(1, '01º LP'), (2, '02º LP'), (3, '03º LP'), (4, '04º LP'), (5, '05º LP'), (6, '06º LP'), (7, '07º LP'), (8, '08º LP')], null=True, verbose_name='Próximo Número da LP')),
                ('proximo_lp', models.DateField(blank=True, null=True, verbose_name='Próximo LP')),
                ('mes_proximo_lp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mês do Próximo LP')),
                ('ano_proximo_lp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano do Próximo LP')),
                ('situacao_lp', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Concedido', 'Concedido'), ('Concluído', 'Concluído')], default='Aguardando', max_length=30, verbose_name='Situação da LP')),
                ('data_concessao_lp', models.DateField(blank=True, null=True, verbose_name='Data de Concessão da LP')),
                ('bol_g_pm_lp', models.CharField(blank=True, max_length=50, null=True, verbose_name='BOL GPm LP')),
                ('data_publicacao_lp', models.DateField(blank=True, null=True, verbose_name='Data Publicação LP')),
                ('lancamento_sipa', models.BooleanField(default=False, verbose_name='Lançamento no SIPA')),
                ('status_lp', models.CharField(choices=[('AGUARDANDO_REQUISITOS', 'Aguardando Requisitos'), ('APTA_CONCESSAO', 'Apta para Concessão'), ('CONCEDIDA', 'Concedida'), ('EM_GOZO', 'Em Gozo'), ('CONCLUIDA', 'Concluída'), ('PENDENTE_SIPA', 'Pendente Lançamento SIPA'), ('INDENIZADA', 'Indenizada'), ('SOBRESTADA', 'Sobrestada')], default='AGUARDANDO_REQUISITOS', max_length=30, verbose_name='Status da LP')),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efetivo.cadastro', verbose_name='Cadastro')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lps_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lps_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('usuario_conclusao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lps_concluidas', to=settings.AUTH_USER_MODEL, verbose_name='Concluído por')),
            ],
            options={
                'verbose_name': 'Licença Prêmio',
                'verbose_name_plural': 'Licenças Prêmio',
                'ordering': ['cadastro__nome_de_guerra', 'numero_lp'],
                'unique_together': {('cadastro', 'numero_lp')},
            },
        ),
        migrations.CreateModel(
            name='HistoricoLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('situacao_lp', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Concedido', 'Concedido'), ('Concluído', 'Concluído')], max_length=30, verbose_name='Situacao da LP')),
                ('status_lp', models.CharField(choices=[('AGUARDANDO_REQUISITOS', 'Aguardando Requisitos'), ('APTA_CONCESSAO', 'Apta para Concessão'), ('CONCEDIDA', 'Concedida'), ('EM_GOZO', 'Em Gozo'), ('CONCLUIDA', 'Concluída'), ('PENDENTE_SIPA', 'Pendente Lançamento SIPA'), ('INDENIZADA', 'Indenizada'), ('SOBRESTADA', 'Sobrestada')], max_length=30, verbose_name='Status da LP')),
                ('numero_lp', models.PositiveSmallIntegerField(choices=[(1, '01º LP'), (2, '02º LP'), (3, '03º LP'), (4, '04º LP'), (5, '05º LP'), (6, '06º LP'), (7, '07º LP'), (8, '08º LP')], verbose_name='Número da LP')),
                ('data_ultimo_lp', models.DateField(verbose_name='Data do Último LP')),
                ('data_inicio_periodo', models.DateField(verbose_name='Início do Período Aquisitivo')),
                ('numero_prox_lp', models.PositiveSmallIntegerField(blank=True, choices=[(1, '01º LP'), (2, '02º LP'), (3, '03º LP'), (4, '04º LP'), (5, '05º LP'), (6, '06º LP'), (7, '07º LP'), (8, '08º LP')], null=True, verbose_name='Próximo Número da LP')),
                ('proximo_lp', models.DateField(blank=True, null=True, verbose_name='Próximo LP')),
                ('mes_proximo_lp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mês do Próximo LP')),
                ('ano_proximo_lp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano do Próximo LP')),
                ('dias_desconto_lp', models.PositiveSmallIntegerField(default=0, verbose_name='Dias de Desconto LP')),
                ('bol_g_pm_lp', models.CharField(blank=True, max_length=50, null=True, verbose_name='BOL GPm LP')),
                ('data_publicacao_lp', models.DateField(blank=True, null=True, verbose_name='Data Publicação LP')),
                ('data_concessao_lp', models.DateField(blank=True, null=True, verbose_name='Data de Concessão da LP')),
                ('lancamento_sipa', models.BooleanField(default=False, verbose_name='Lançamento no SIPA')),
                ('observacoes_historico', models.TextField(blank=True, verbose_name='Observações do Histórico')),
                ('usuario_alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_lp', to='lp.lp')),
            ],
            options={
                'verbose_name': 'Histórico de Licença Prêmio',
                'verbose_name_plural': 'Históricos de Licenças Prêmio',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
