# Generated by Django 5.2 on 2025-06-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicolp',
            name='data_inicio_periodo',
        ),
        migrations.RemoveField(
            model_name='lp',
            name='data_inicio_periodo',
        ),
        migrations.AlterField(
            model_name='historicolp',
            name='numero_lp',
            field=models.PositiveSmallIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08')], verbose_name='Número da LP'),
        ),
        migrations.AlterField(
            model_name='historicolp',
            name='numero_prox_lp',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08')], null=True, verbose_name='Próximo Número da LP'),
        ),
        migrations.AlterField(
            model_name='lp',
            name='numero_lp',
            field=models.PositiveSmallIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08')], verbose_name='Número da LP'),
        ),
        migrations.AlterField(
            model_name='lp',
            name='numero_prox_lp',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08')], null=True, verbose_name='Próximo Número da LP'),
        ),
    ]
