# Generated by Django 5.2 on 2025-06-19 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp', '0003_alter_lp_options_alter_lp_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicolp',
            options={'verbose_name': 'Histórico da LP', 'verbose_name_plural': 'Histórico das LPs'},
        ),
        migrations.AlterModelOptions(
            name='lp',
            options={'verbose_name': 'Licença Prêmio', 'verbose_name_plural': 'Licenças Prêmio'},
        ),
        migrations.AddField(
            model_name='historicolp',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão (Histórico)'),
        ),
        migrations.AddField(
            model_name='historicolp',
            name='usuario_conclusao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_lps_concluidas', to=settings.AUTH_USER_MODEL, verbose_name='Concluído por (Histórico)'),
        ),
        migrations.AlterField(
            model_name='historicolp',
            name='data_ultimo_lp',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Último LP'),
        ),
        migrations.AlterField(
            model_name='historicolp',
            name='lp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lp.lp', verbose_name='LP'),
        ),
        migrations.AlterField(
            model_name='historicolp',
            name='status_lp',
            field=models.CharField(choices=[('aguardando_requisitos', 'Aguardando Requisitos'), ('apta_concessao', 'Apta para Concessão'), ('lancado_sipa', 'Lançado no SIPA'), ('concedido', 'Concedido'), ('publicado', 'Publicado'), ('concluido', 'Concluído')], max_length=30, verbose_name='Status da LP'),
        ),
        migrations.AlterField(
            model_name='lp',
            name='data_ultimo_lp',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Último LP'),
        ),
        migrations.AlterField(
            model_name='lp',
            name='status_lp',
            field=models.CharField(choices=[('aguardando_requisitos', 'Aguardando Requisitos'), ('apta_concessao', 'Apta para Concessão'), ('lancado_sipa', 'Lançado no SIPA'), ('concedido', 'Concedido'), ('publicado', 'Publicado'), ('concluido', 'Concluído')], default='aguardando_requisitos', max_length=30, verbose_name='Status da LP'),
        ),
    ]
