# Generated by Django 5.2 on 2025-06-30 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efetivo', '0009_alter_historicodetalhessituacao_options_and_more'),
        ('lp', '0004_alter_historicolp_options_alter_lp_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LP_fruicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lp', models.PositiveSmallIntegerField(verbose_name='Número da LP Concluída')),
                ('data_concessao_lp', models.DateField(blank=True, null=True, verbose_name='Data de Concessão da LP')),
                ('bol_g_pm_lp', models.CharField(blank=True, max_length=50, null=True, verbose_name='BOL GPm LP')),
                ('data_publicacao_lp', models.DateField(blank=True, null=True, verbose_name='Data Publicação LP')),
                ('tipo_periodo_afastamento', models.PositiveSmallIntegerField(blank=True, choices=[(15, '15 Dias'), (30, '30 Dias'), (45, '45 Dias'), (60, '60 Dias'), (75, '75 Dias'), (90, '90 Dias')], null=True, verbose_name='Tipo de Período de Afastamento')),
                ('tipo_choice', models.CharField(blank=True, choices=[('fruicao', 'Fruição'), ('pecunia', 'Pecúnia')], max_length=10, null=True, verbose_name='Tipo de Escolha')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efetivo.cadastro', verbose_name='Cadastro')),
                ('lp_concluida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='previsao_associada', to='lp.lp', verbose_name='LP Concluída Associada')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previsoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previsoes_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Fruição de LP',
                'verbose_name_plural': 'Fruições de LPs',
                'ordering': ['cadastro', 'numero_lp'],
            },
        ),
    ]
