# Generated by Django 5.2 on 2025-06-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adicional', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lp',
            name='cadastro',
        ),
        migrations.RemoveField(
            model_name='lp',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='lp',
            name='user_updated',
        ),
        migrations.DeleteModel(
            name='HistoricoLP',
        ),
        migrations.DeleteModel(
            name='LP',
        ),
    ]
