# Generated by Django 5.2 on 2025-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocadastro',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
