# Generated by Django 5.1.4 on 2025-03-12 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicional', '0001_initial'),
        ('efetivo', '0002_detalhessituacao_prontidao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicocadastro',
            old_name='Cadastro_adicional',
            new_name='cadastro_adicional',
        ),
        migrations.AlterField(
            model_name='cadastro_adicional',
            name='cadastro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='efetivo.cadastro'),
        ),
    ]
