# Generated by Django 5.1.4 on 2025-03-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicional', '0002_rename_cadastro_adicional_historicocadastro_cadastro_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro_adicional',
            name='situacao_adicional',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Concedido', 'Concedido')], default='Aguardando', max_length=30),
        ),
        migrations.AlterField(
            model_name='cadastro_adicional',
            name='situacao_lp',
            field=models.CharField(choices=[('Aguardando', 'Aguardando'), ('Concedido', 'Concedido')], default='Aguardando', max_length=30),
        ),
    ]
