# Generated by Django 5.2 on 2025-05-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicional', '0002_alter_historicocadastro_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocadastro',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
    ]
