# Generated by Django 5.2 on 2025-05-04 15:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adicional', '0003_alter_historicocadastro_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicocadastro',
            name='data_ultimo_adicional',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Último Adicional'),
        ),
        migrations.AlterField(
            model_name='historicocadastro',
            name='numero_adicional',
            field=models.PositiveSmallIntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08')], default=1, verbose_name='Número do Adicional'),
        ),
    ]
