# Generated by Django 4.2.7 on 2025-11-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('url', models.URLField(max_length=2000, verbose_name='URL')),
                ('icon', models.CharField(blank=True, help_text='Ex: fas fa-link, fab fa-docker, ou um emoji 🐳', max_length=50, verbose_name='Ícone')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Link Útil',
                'verbose_name_plural': 'Links Úteis',
                'ordering': ['order', 'name'],
            },
        ),
    ]
