# Generated by Django 5.2.4 on 2025-07-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dig',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='posto_grad',
            field=models.CharField(blank=True, choices=[('', ' '), ('Cel PM', 'Cel PM'), ('Ten Cel PM', 'Ten Cel PM'), ('Maj PM', 'Maj PM'), ('CAP PM', 'Cap PM'), ('1º Ten PM', '1º Ten PM'), ('1º Ten QAPM', '1º Ten QAOPM'), ('2º Ten PM', '2º Ten PM'), ('2º Ten QAPM', '2º Ten QAOPM'), ('Asp OF PM', 'Asp OF PM'), ('Subten PM', 'Subten PM'), ('1º Sgt PM', '1º Sgt PM'), ('2º Sgt PM', '2º Sgt PM'), ('3º Sgt PM', '3º Sgt PM'), ('Cb PM', 'Cb PM'), ('Sd PM', 'Sd PM'), ('Sd PM 2ºCL', 'Sd PM 2ºCL')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='re',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.CharField(blank=True, choices=[('administrativo', 'Administrativo'), ('operacional', 'Operacional')], max_length=15, null=True),
        ),
    ]
