# Generated by Django 4.2.7 on 2025-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="assunto",
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="documento",
            name="data_documento",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="documento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PDF", "PDF"),
                    ("VIDEO", "Vídeo"),
                    ("AUDIO", "Áudio"),
                    ("DOC", "Documento"),
                    ("SHEET", "Planilha"),
                    ("IMAGEM", "Imagem"),
                    ("TEXT", "Texto"),
                    ("OUTRO", "Outro"),
                ],
                db_index=True,
                default="OUTRO",
                max_length=10,
            ),
        ),
    ]
